name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test suite'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.9', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox tox-gh-actions
    - name: Run tox
      run: tox . -vvv

  lint_and_docs:
    name: 'Lint and Docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qy npm
        npm install -g prettier
    - name: Install Python dependencies
      run: |
        python3 -m pip install -r requirements-extra.txt
    - name: Install Package
      run: |
        python3 -m pip install -e .
    - name: Lint sources
      run: |
        make lint
    - name: Build docs
      run: |
        make docs
